name: ruby_event_store-persistent_projections
on:
  schedule:
    - cron: "0 17 * * *"
  push:
    paths:
      - "contrib/ruby_event_store-persistent_projections/**"
      - ".github/workflows/ruby_event_store-persistent_projections.yml"
      - "support/**"
  pull_request:
    types: [opened, reopened]
    paths:
      - "contrib/ruby_event_store-persistent_projections/**"
      - ".github/workflows/ruby_event_store-persistent_projections.yml"
      - "support/**"
jobs:
  test:
    runs-on: ${{ matrix.os }}
    env:
      WORKING_DIRECTORY: contrib/ruby_event_store-persistent_projections
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
      DATABASE_URL: ${{ matrix.database }}
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: rails_event_store
          MYSQL_ROOT_PASSWORD: secret
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: ruby-3.0
            gemfile: Gemfile
            os: ubuntu-20.04
            database: mysql2://root:secret@127.0.0.1/rails_event_store
          - ruby: ruby-2.7
            gemfile: Gemfile
            os: ubuntu-20.04
            database: mysql2://root:secret@127.0.0.1/rails_event_store
          - ruby: ruby-2.6
            gemfile: Gemfile
            os: ubuntu-20.04
            database: mysql2://root:secret@127.0.0.1/rails_event_store
          - ruby: ruby-2.5
            gemfile: Gemfile
            os: ubuntu-20.04
            database: mysql2://root:secret@127.0.0.1/rails_event_store
    steps:
      - uses: actions/checkout@v2
      - run: test -e ${{ matrix.gemfile }}.lock
        working-directory: ${{ env.WORKING_DIRECTORY }}
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
          working-directory: ${{ env.WORKING_DIRECTORY }}
      - run: make test
        working-directory: ${{ env.WORKING_DIRECTORY }}

  mutate:
    runs-on: ${{ matrix.os }}
    env:
      WORKING_DIRECTORY: contrib/ruby_event_store-persistent_projections
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
      DATABASE_URL: ${{ matrix.database }}
      MUTANT_JOBS: 1
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: ruby-2.7
            gemfile: Gemfile
            os: ubuntu-20.04
            database: mysql2://root:secret@127.0.0.1/rails_event_store
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: test -e ${{ matrix.gemfile }}.lock
        working-directory: ${{ env.WORKING_DIRECTORY }}
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
          working-directory: ${{ env.WORKING_DIRECTORY }}
      - run: make mutate-changes
        working-directory: ${{ env.WORKING_DIRECTORY }}
